reportType: error
slent: true
whiteList:
    - parentPattern: "DispatchQueue\\..*"
      functionName: "async.*"
    - parentPattern: "DispatchQueue\\..*"
      functionName: "sync.*"
    - parentPattern: "UIView"
      functionName: "animate"
    - parentPattern: "Task"
      functionName: ".*"
    - functionName: "Task"
excludedFiles:
    - ".*/\\.build/.*"
    - ".*/vendor/bundle/.*"
    - ".*/Pods/.*"
