reportType: error
slent: true
whiteList:
    - parentPattern: "DispatchQueue.*"
      functionName: "async*"
    - parentPattern: "DispatchQueue.*"
      functionName: "sync*"
excludedFiles:
    - "*/.build/*"
    - "*/vendor/bundle/*"
    - "*/Pods/*"
